[package]
name = "order"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
actix-web = { workspace = true }
view = { workspace = true }
