[workspace]
members = [
    "api"
,   "controller"
,   "model"
,   "repository"
,   "view"
]
resolver = "2"

[workspace.dependencies]
model = { path = "model" }
view = { path = "view" }
controller = { path = "controller" }
repository = { path = "repository" }
sqlx = { version = "0.8.2", features = ["chrono", "postgres"]}
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.81"
tokio = "1.39.2"
actix-web = "4"
